### ISSUE TITLE
0-Set Up 

### ISSUE THREAD

**Issue by samirm00** [samirm00/js-study-guide#1]
- [ ] Fork the repo js-study-guide
- [x] Add collaborators
- [x] Turn on GitHub pages
- [x] Create a project board js-study-guide-project-board
- [x] Write the strategy plan

**Comment by samirm00** [comment]
Everything is done here , we can close the issue

**Comment by KrystynaMil** [comment]
Check :)

**Comment by Houcinos** [comment]
Super!

**Comment by samirm00** [comment]
@MarieBelyse  can you confirm !

**Comment by MarieBelyse** [comment]
goog

**Comment by MarieBelyse** [comment]
good
