### ISSUE TITLE
1- Design (Figma)

### ISSUE THREAD

**Issue by samirm00** [samirm00/js-study-guide#2]
- [x] [Create a Figma file Js-Study-Guide]( https://www.figma.com/file/BRmkGPOl6GzHtWZjesTuIz/JS-Study-Guide?node-id=0%3A1)
- [x] Share the link with the collaborators
- [x] Design the website

**Comment by samirm00** [comment]
@Houcinos @KrystynaMil @MarieBelyse   Good so far

**Comment by KrystynaMil** [comment]
Very good so far

**Comment by MarieBelyse** [comment]
nice

**Comment by samirm00** [comment]
I am done with Figma , how about you guys @Houcinos @KrystynaMil @MarieBelyse

**Comment by MarieBelyse** [comment]
i am done too
