### ISSUE TITLE
7-Final touches

### ISSUE THREAD

**Issue by samirm00** [samirm00/js-study-guide#7]
- [x] Make sure everything working properly
- [x] Correct the errors in html and CSS files

**Comment by samirm00** [comment]
@Houcinos @KrystynaMil @MarieBelyse  I have validated HTML and CSS for home and reference pages , you can check your html and CSS validations , just click in your page then press Validate HTML and you will see if you have any errors , the same for Validate CSS ( remember , you have to click on your page first then validation) .
@KrystynaMil  https://samirm00.github.io/js-study-guide/variables.html
@Houcinos  https://samirm00.github.io/js-study-guide/loops.html 
@MarieBelyse https://samirm00.github.io/js-study-guide/operations.html

@MarieBelyse   your page has different header and footer style than the rest pages , you third snippet link is not correct 

@Houcinos  your first snippet link is not correct  , regards,

**Comment by Houcinos** [comment]
@samirm00 I did the check and I have some errors which do not make any sense for me. 
![image](https://user-images.githubusercontent.com/57623782/99078120-1c13b680-25be-11eb-804a-7415bb589ce3.png)

**Comment by MarieBelyse** [comment]
@Samir sorry for delay I am going to correct it

**Comment by samirm00** [comment]
@Houcinos  they do make sense , <i><b>  text </b></i> , they suppose to be like that , 

then you have some extra end tags without <b> start tag

**Comment by samirm00** [comment]
first <b>    then  <i>       your text   then   </i> close i first then close </b>

**Comment by samirm00** [comment]
GitHub format the text automatically my point if  you start bold start then italic start you have to close italic end first then bold end
